# Netlify configuration for Next.js
[build]
  command = "npm run build"
  publish = ".next"

# Handle Next.js server-side rendering
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' https://*.supabase.co https://*.supabase.in https://*.supabase.net https://fapublicdata.blob.core.windows.net;" 